### ISSUE TITLE
New Ion template doesn't have the cp code behavior under the default rule

### ISSUE THREAD

**Issue by jaescalo** [akamai/cli-onboard#19]
The current code looks in the default rule for the CP code behavior to update it with the newly created CP code. However, the newer Ion template doesn't have a CP code behavior in the default rule, it is located under Augmented Insights -> Traffic Reporting and this causes the CP code update feature not to work on the newer template.

**Comment by pwongcha** [comment]
Hi Jaime, 
We publish cli onboard 2.0.0.  Could you please let us know if you still have the issue?

**Comment by aetsai** [comment]
Please reopen if still an issue
