### ISSUE TITLE
single_host() in akamai-onboard.py doe not work

### ISSUE THREAD

**Issue by kimsmin** [akamai/cli-onboard#28]
[Issue]
    # Override default
    util.onboard_override_default(onboard, setup, cli_mode='single-host')

    # wrap_api.get_groups_without_parent() returns '' when grp has a 
parentGroupId', which is very common in customers' environments.
    # As a result, group_id value becomes '' and it causes 'no group_id' error when we call the /papi/v1/edgehostnames API.
    util.validate_group_id(onboard, wrap_api.get_groups_without_parent())

    util.validateSetupSteps(onboard, wrap_api, cli_mode='single_host')
        return groups

**Comment by pwongcha** [comment]
Thanks for reporting the issue. Can you share the group ID you use?  if not, please get in touch with me/Julie via internal Akamai Webex.  I can't find you on the contacts website

**Comment by pwongcha** [comment]
Issue reviewed
Action plan:
1. Alllow an optional value group_id in the JSON file 
2. Update README.md -- need clarification and fix typo
