### ISSUE TITLE
Support Group_ID for Multi-hosts mode

### ISSUE THREAD

**Issue by shahriarNK** [akamai/cli-onboard#43]
The documentation (Readme file) suggests that Group_ID is optional for the Single-Host and Multi-Hosts mode of the CLI. Hence, if Group_ID is provided, the config will be created in the specific group; if not it will be created in the top level group.

This works exactly as described for Single-Hosts mode but does not work as expected in the the Multi-Hosts mode (i.e., config is always created in the top level group whether Group_ID is provided or not).

Thank you for addressing this issue.

**Comment by pwongcha** [comment]
Acknowledge.  We will support `group_id` for `multi-hosts` mode
